# Generated by Django 4.2.7 on 2023-12-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_n',
            new_name='username',
        ),
    ]
